import org.code.neighborhood.*;
public class AsphaltPainter extends PainterPlus{
    public void paintCanvas(String color){
    while(canMove()){
      paint(color);
      move();
      if(!canMove("east")){
        turnRight();
      }
      if(!canMove("west")){
        turnLeft();
      }
    }
  }
  public void paintCactus(String color){
    if(isFacingEast()){
      turnLeft();
    }
    if(isFacingSouth()){
      turnLeft();
      turnLeft();
    }
    if(isFacingWest()){
      turnRight();
    }
    while(hasPaint()){
      paint("green");
      move();
      paint("green"); 
      move();
      paint("green");
      move();
      paint("green");
      move();
      paint("green");
      turnLeft();
      turnLeft();
      move();
      move();
      turnRight();
      move();
      paint("green");
      turnRight();
      move();
      paint("green");
      move();
      paint("green");
      move();
      paint("green");
      turnRight();
      move();
      move();
      turnRight();
      move();
      move();
      paint("green");
      move();
      paint("green");
    }
  }
}